// client/projects/website/src/app/modules/about/about.component.ts
import {Component, OnInit, ChangeDetectionStrategy} from '@angular/core';

@Component({
  selector: 'hg-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AboutComponent implements OnInit {
  constructor() {}

  ngOnInit() {}
}

<section class="bg-img p-y-m">
  <div class="grid">
    <div class="col-6 col-m-8 col-s-10 col-xs-12">
      <h1 class="c-dt-primary"><span class="title-dt">About us</span></h1>
    </div>
  </div>
</section>

<section class="p-b-l">
  <div class="grid">
    <div class="col-6 col-m-8 col-s-10 col-xs-12">

      <div class="read-format">

        <h3>The Human Glycome Project</h3>

        <p>The Human Glycome Project (HGP) is led by a consortium of research groups that shares a common goal of aiming to define the structures and functions of human glycoconjugates. Completion of the human genome project opened multiple new opportunities to study and understand human health, but it also led to the realization that the genome is only one of the elements that control life, and that multiple additional layers of complexity exist. One of the most important elements of the complexity of life is protein glycosylation. It is the most intricate posttranslational modification of proteins and alterations in glycosylation microheterogeneity (differences in site-specific glycosylation) can have effects analogous to coding mutations. Without the knowledge about glycan structure and their impact on function it is impossible to understand the function of individual proteins or complex multiprotein and multicellular systems.</p>

        <p>We aim to create new opportunities for researchers focused on unravelling the human glycome by bringing together at one place</p>

        <ul>
          <li>the comprehensive list of projects working on human glycome</li>
          <li>resources and discounted analysis offers by associate members available to any full member of Human Glycome Project</li>
          <li>Glycan databases</li>
          <li>Platform for free education about the relevance of Human Glycome</li>
          <li>Community of scientists, industry, institutions, journalist and general public dedicated to mission and vision of the human glycome project</li>
        </ul>

        <h6>Our vision</h6>

        <p>In-depth understanding of the effect that glycans have on the structure and function of individual proteins, lipids or as part of polysaccharides in health and disease will help us to understand functional significance of inter- and intra-individual differences in glycome composition. Moreover, it will help us understand how they associate with the pathogenicity of diseases such as cancer and chronic diseases. This knowledge will catalyze novel translational developments that will position glycomics as a major technology for disease identification, patient stratification and therapy response.</p>

        <h6>Our mission</h6>

        <ul>
          <li>Map glycan structures in a protein and site-specific manner and embark on the challenge of recording inter- and intra-individual variability of all glycoproteins in all human cells and tissues</li>
          <li>Determine the impact of individual glycans on the function of their glycoconjugates (proteins or lipids) in health and disease</li>
          <li>Understand the mechanisms, pathways and systems that regulate glycosylation, and how this regulation is compromised in various states of health and disease.</li>
          <li>Describe the “normal” human glycome in a body fluid and tissue specific manner and the range of natural variation to establish a reference glycome using quantitative glycomic approaches</li>
          <li>Develop, standardize and disseminate protocols, reagents, analytical tools and reporting guidelines to promote best research practices in glycomics</li>
          <li>Create a public database of the human glycome data and link it with other databases to integrate glycomics into existing systems biology endeavours</li>
          <li>Promote education in the field of glycoscience</li>
        </ul>

        <h6>Organisational structure of the Human Glycome Project</h6>

        <p><strong>Co-Directors</strong>:
          <br>
          Richard Cummings and Gordan Lauc</p>

        <p><strong>Steering Committee</strong>:
          <br>
          Rick Cummings, USA<br>
          Daniel Kolarich, Australia<br>
          Sabine Flitsch , UK<br>
          Gordan Lauc, Croatia<br>
          Michael Pierce, USA<br>
          Pauline Rudd, Singapore<br>
          Manfred Wuhrer, The Netherlands<br>
          Wei Wang, China
        </p>

        <h6>Divisions of the Human Glycome Project</h6>

        <ol>
          <li>Diversity of the human glycome (Director: Richard Cummings)</li>
          <li>Inter-individual variability of the human body fluids glycome (Director: Gordan Lauc)</li>
          <li>Inter-individual variability of the human tissue glycome (Director: Prof Daniel Kolarich)</li>
          <li>Functional relevance and regulation of the human glycome (Director: Mike Pierce)</li>
          <li>Analytical methods and standards for glycoscience (Director: Manfred Wuhrer)</li>
        </ol>

      </div>
    </div>
  </div>
</section>

// client2/src/routes/about/+page.svelte
<section class="bg-img p-y-m">
  <div class="grid">
    <div class="col-6 col-m-8 col-s-10 col-xs-12">
      <h1 class="c-dt-primary"><span class="title-dt">About us</span></h1>
    </div>
  </div>
</section>

<section class="p-b-l">
  <div class="grid">
    <div class="col-6 col-m-8 col-s-10 col-xs-12">
      <div class="read-format">
        <h3>The Human Glycome Project</h3>

        <p>
          The Human Glycome Project (HGP) is led by a consortium of research
          groups that shares a common goal of aiming to define the structures
          and functions of human glycoconjugates. Completion of the human genome
          project opened multiple new opportunities to study and understand
          human health, but it also led to the realization that the genome is
          only one of the elements that control life, and that multiple
          additional layers of complexity exist. One of the most important
          elements of the complexity of life is protein glycosylation. It is the
          most intricate posttranslational modification of proteins and
          alterations in glycosylation microheterogeneity (differences in
          site-specific glycosylation) can have effects analogous to coding
          mutations. Without the knowledge about glycan structure and their
          impact on function it is impossible to understand the function of
          individual proteins or complex multiprotein and multicellular systems.
        </p>

        <p>
          We aim to create new opportunities for researchers focused on
          unravelling the human glycome by bringing together at one place
        </p>

        <ul>
          <li>the comprehensive list of projects working on human glycome</li>
          <li>
            resources and discounted analysis offers by associate members
            available to any full member of Human Glycome Project
          </li>
          <li>Glycan databases</li>
          <li>
            Platform for free education about the relevance of Human Glycome
          </li>
          <li>
            Community of scientists, industry, institutions, journalist and
            general public dedicated to mission and vision of the human glycome
            project
          </li>
        </ul>

        <h6>Our vision</h6>

        <p>
          In-depth understanding of the effect that glycans have on the
          structure and function of individual proteins, lipids or as part of
          polysaccharides in health and disease will help us to understand
          functional significance of inter- and intra-individual differences in
          glycome composition. Moreover, it will help us understand how they
          associate with the pathogenicity of diseases such as cancer and
          chronic diseases. This knowledge will catalyze novel translational
          developments that will position glycomics as a major technology for
          disease identification, patient stratification and therapy response.
        </p>

        <h6>Our mission</h6>

        <ul>
          <li>
            Map glycan structures in a protein and site-specific manner and
            embark on the challenge of recording inter- and intra-individual
            variability of all glycoproteins in all human cells and tissues
          </li>
          <li>
            Determine the impact of individual glycans on the function of their
            glycoconjugates (proteins or lipids) in health and disease
          </li>
          <li>
            Understand the mechanisms, pathways and systems that regulate
            glycosylation, and how this regulation is compromised in various
            states of health and disease.
          </li>
          <li>
            Describe the “normal” human glycome in a body fluid and tissue
            specific manner and the range of natural variation to establish a
            reference glycome using quantitative glycomic approaches
          </li>
          <li>
            Develop, standardize and disseminate protocols, reagents, analytical
            tools and reporting guidelines to promote best research practices in
            glycomics
          </li>
          <li>
            Create a public database of the human glycome data and link it with
            other databases to integrate glycomics into existing systems biology
            endeavours
          </li>
          <li>Promote education in the field of glycoscience</li>
        </ul>

        <h6>Organisational structure of the Human Glycome Project</h6>

        <p>
          <strong>Co-Directors</strong>:
          <br />
          Richard Cummings and Gordan Lauc
        </p>

        <p>
          <strong>Steering Committee</strong>:
          <br />
          Rick Cummings, USA<br />
          Daniel Kolarich, Australia<br />
          Sabine Flitsch , UK<br />
          Gordan Lauc, Croatia<br />
          Michael Pierce, USA<br />
          Pauline Rudd, Singapore<br />
          Manfred Wuhrer, The Netherlands<br />
          Wei Wang, China
        </p>

        <h6>Divisions of the Human Glycome Project</h6>

        <ol>
          <li>Diversity of the human glycome (Director: Richard Cummings)</li>
          <li>
            Inter-individual variability of the human body fluids glycome
            (Director: Gordan Lauc)
          </li>
          <li>
            Inter-individual variability of the human tissue glycome (Director:
            Prof Daniel Kolarich)
          </li>
          <li>
            Functional relevance and regulation of the human glycome (Director:
            Mike Pierce)
          </li>
          <li>
            Analytical methods and standards for glycoscience (Director: Manfred
            Wuhrer)
          </li>
        </ol>
      </div>
    </div>
  </div>
</section>
