// client2/src/routes/glyco-databases/+page.svelte
<script lang="ts">
  export let data;
</script>

<div class="grid jc-center bg-img p-y-m">
  <div class="col-6 col-m-8 col-s-10 col-xs-12">
    <h1 class="c-dt-primary"><span class="title-dt">Glyco databases</span></h1>
  </div>
</div>

<section class="p-b-l">
  <div class="grid jc-center">
    <div class="col-6 col-m-8 col-s-10 col-xs-12">
      <div class="read-format">
        <br />
        <p>
          The Human Glycome Project endorses the following glycan databases. To
          include additional database to this list, please send short
          description of the database to the Steering Committee of the Human
          Glycome Project at <a
            href="mailto:info@human-glycome.org?Subject=Glyco%20Database%20Addition%20Request"
            target="_top">info@human-glycome.org</a
          >
        </p>

        <h5>Glyco Databases</h5>
        <ul>
          {#each data.glycoDatabases as database}
            <li>
              <a href={database.link} target="_blank" rel="noopener"
                >{database.link}</a
              >
              -
              <span>{database.name}</span>
            </li>
          {/each}
        </ul>

        <h5 class="m-t-l">Further lists of glyco-databases can be found at:</h5>

        <ul>
          <li>
            <a
              href="https://www.expasy.org/glycomics"
              target="_blank"
              rel="noopener">https://www.expasy.org/glycomics</a
            >
          </li>
          <li>
            <a
              href="http://www.glycoscience.de/db-overview.php"
              target="_blank"
              rel="noopener">http://www.glycoscience.de/db-overview.php</a
            >
          </li>
          <li>
            <a
              href="https://www.ncbi.nlm.nih.gov/glycans/"
              target="_blank"
              rel="noopener">https://www.ncbi.nlm.nih.gov/glycans/</a
            >
          </li>
          <li>
            <a
              href="http://csdb.glycoscience.ru/"
              target="_blank"
              rel="noopener">http://csdb.glycoscience.ru/</a
            >
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

<style lang="scss">
  h5 {
    margin-top: 2rem;
    margin-bottom: 1rem;
  }
  ul {
    list-style: disc;
    padding-left: 1.5rem;
    li {
      margin-bottom: 0.5rem;
    }
  }
  a {
    color: dodgerblue;
    text-decoration: underline;
  }
</style>

// client/projects/website/src/app/modules/glyco-databases/glyco-databases.component.ts
import {
  Component,
  OnInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef
} from '@angular/core';
import {Observable} from 'rxjs';
import {finalize, map} from 'rxjs/operators';
import {GlycoDatabases} from '../../shared/interfaces/collections/glyco-databases.interface';
import {JasperoApiService} from '../../shared/services/jaspero-api/jaspero-api.service';

@Component({
  selector: 'hg-glyco-databases',
  templateUrl: './glyco-databases.component.html',
  styleUrls: ['./glyco-databases.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class GlycoDatabasesComponent implements OnInit {
  constructor(
    private _jasperoApi: JasperoApiService,
    private _cdr: ChangeDetectorRef
  ) {}

  loading = true;
  glycoDatabases$: Observable<GlycoDatabases[]>;

  ngOnInit() {
    this.glycoDatabases$ = this._jasperoApi
      .get<GlycoDatabases>('glyco-databases')
      .pipe(
        map(res => res.data),
        finalize(() => {
          this.loading = false;
          this._cdr.detectChanges();
        })
      );
  }
}

<div class="page-loading" *ngIf="loading">
  <mat-spinner [diameter]="40"></mat-spinner>
</div>

<section class="bg-img p-y-m">
  <div class="grid">
    <div class="col-6 col-m-8 col-s-10 col-xs-12">
      <h1 class="c-dt-primary"><span class="title-dt">Glyco databases</span></h1>
    </div>
  </div>
</section>

<section class="p-b-l">
  <div class="grid">
    <div class="col-6 col-m-8 col-s-10 col-xs-12">
      <div class="read-format" [class.hidden]="loading">

        <br>
        <p>The Human Glycome Project endorses the following glycan databases. To include additional database to this list, please send short description of the database to the Steering Committee of the Human Glycome Project at <a href="mailto:info@human-glycome.org?Subject=Glyco%20Database%20Addition%20Request" target="_top">info@human-glycome.org</a></p>

        <h5>Glyco Databases</h5>
        <ul>
          <li *ngFor="let database of glycoDatabases$ | async">
            <a [href]="database.link" target="_blank" rel="noopener">{{database.link}}</a> -
            <span>{{database.name}}</span>
          </li>
        </ul>

        <h5>Further lists of glyco-databases can be found at:</h5>

        <ul>
          <li>
            <a href="https://www.expasy.org/glycomics" target="_blank" rel="noopener">https://www.expasy.org/glycomics</a>
          </li>
          <li>
            <a href="http://www.glycoscience.de/db-overview.php" target="_blank" rel="noopener">http://www.glycoscience.de/db-overview.php</a>
          </li>
          <li>
            <a href="https://www.ncbi.nlm.nih.gov/glycans/" target="_blank" rel="noopener">https://www.ncbi.nlm.nih.gov/glycans/</a>
          </li>
          <li>
            <a href="http://csdb.glycoscience.ru/" target="_blank" rel="noopener">http://csdb.glycoscience.ru/</a>
          </li>
        </ul>

      </div>
    </div>
  </div>
</section>
