// client2/src/routes/projects/+page.svelte
<script lang="ts">
  export let data;
</script>

<div class="grid jc-center bg-img p-y-m">
  <div class="col-6 col-m-8 col-s-10 col-xs-12">
    <h1 class="c-dt-primary"><span class="title-dt">Projects</span></h1>
  </div>
</div>

<section class="p-b-l">
  <div class="grid jc-center">
    <div class="col-6 col-m-8 col-s-10 col-xs-12" style="overflow-y: auto">
      <div class="read-format">
        <br />
        <p>
          Individual, independently funded, projects that contribute to the
          goals of the Human Glycome Project are:
        </p>

        {#each data.projects as group}
          <article>
            <h6>{group.category}</h6>
            <table>
              <thead>
                <tr>
                  <th>Short Name</th>
                  <th>Description</th>
                  <th>Coordinating Institution</th>
                </tr>
              </thead>
              <tbody>
                {#each group.projects as project}
                  <tr>
                    <td>{project.shortName || project.title}</td>
                    <td>{project.description || project.shortDescription}</td>
                    <td>{project.coordinatingInstitution || ''}</td>
                  </tr>
                {/each}
              </tbody>
            </table>
            <br />
          </article>
        {/each}

        <h6>
          To include your projects in projects of the Human Glycome Project,
          please send short description of the project to the Steering Committee
          of the Human Glycome Project at
          <a
            href="mailto:info@human-glycome.org?Subject=Project%20Addition%20Request"
            target="_top">info@human-glycome.org</a
          >
        </h6>
      </div>
    </div>
  </div>
</section>

// client/projects/website/src/app/modules/projects/projects.component.ts
import {
  Component,
  OnInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef
} from '@angular/core';
import {Observable} from 'rxjs';
import {map} from 'rxjs/operators';
import {Projects} from '../../shared/interfaces/collections/projects.interface';
import {FirestoreCollection} from '../../shared/enums/firestore-collection.enum';
import {AngularFirestore} from '@angular/fire/firestore';

@Component({
  selector: 'hg-projects',
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class ProjectsComponent implements OnInit {
  constructor(
    private afs: AngularFirestore,
    private cdr: ChangeDetectorRef
  ) {}

  loading = true;
  categories$: Observable<Array<{category: string; projects: Projects[]}>>;

  ngOnInit() {
    this.categories$ = this.afs
      .collection(FirestoreCollection.Projects)
      .snapshotChanges()
      .pipe(
        map(actions =>
          actions.map(action => ({
            id: action.payload.doc.id,
            ...(action.payload.doc.data() as any)
          })).reduce((acc, cur) => {
            const index = acc.findIndex(item => item.category === cur.category);

            if (index === -1) {
              acc.push({
                category: cur.category,
                projects: [cur]
              });
            } else {
              acc[index].projects.push(cur);
            }
            this.loading = false;
            return acc;
          }, [])
        )
      );
  }
}

<div class="page-loading" *ngIf="loading">
  <mat-spinner [diameter]="40"></mat-spinner>
</div>

<section class="bg-img p-y-m">
  <div class="grid">
    <div class="col-6 col-m-8 col-s-10 col-xs-12">
      <h1 class="c-dt-primary"><span class="title-dt">Projects</span></h1>
    </div>
  </div>
</section>

<section class="p-b-l">
  <div class="grid">
    <div class="col-6 col-m-8 col-s-10 col-xs-12" style="overflow-y: auto">

      <div class="read-format">

        <br>
        <p>Individual, independently funded, projects that contribute to the goals of the Human Glycome Project are:</p>

        <article *ngFor="let category of categories$ | async">
          <h6>{{category.category}}</h6>
          <table>
            <tr>
              <th>Short Name</th>
              <th>Description</th>
              <th>Coordinating Institution</th>
            </tr>
            <tr *ngFor="let project of category.projects">
              <td>{{project.shortName}}</td>
              <td>{{project.description}}</td>
              <td>{{project.coordinatingInstitution}}</td>
            </tr>
          </table>
          <br>
        </article>

        <h6>
          To include your projects in projects of the Human Glycome Project, please send short description of the project to the Steering Committee of the Human Glycome Project at
          <a href="mailto:info@human-glycome.org?Subject=Project%20Addition%20Request" target="_top">info@human-glycome.org</a>
        </h6>

      </div>

    </div>
  </div>
</section>
